mkdir .git/hooks/ if it does not exist.
Fixes the following error observed running `patatt install-hook` in a
fresh kernel checkout:

Traceback (most recent call last):
  File "/usr/local/google/home/ndesaulniers/.local/bin/patatt", line 8, in <module>
    sys.exit(command())
  File "/usr/local/google/home/ndesaulniers/.local/lib/python3.9/site-packages/patatt/__init__.py", line 1204, in command
    _args.func(_args, config)
  File "/usr/local/google/home/ndesaulniers/.local/lib/python3.9/site-packages/patatt/__init__.py", line 1125, in cmd_install_hook
    with open(hookfile, 'w') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/android0/linux-next/.git/hooks/sendemail-validate'

Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>